- name: Installing dependencies
  apt: name={{item}} state=installed
  with_items:
    - s3cmd
    - git

- name: Fetch alpenglow repository
  git:
    repo: https://github.com/tpawlowski/alpenglow.git
    dest: /home/ubuntu/alpenglow
    version: master
  become: yes
  become_user: "{{ansible_user}}"

- name: Installing venv
  command: virtualenv /home/ubuntu/alpenglow/venv_heron creates="/home/ubuntu/alpenglow/venv_heron"
  become: yes
  become_user: "{{ansible_user}}"

- name: Install requirements
  pip:
    requirements=/home/ubuntu/alpenglow/requirements.txt
    virtualenv=/home/ubuntu/alpenglow/venv_heron
  become: yes
  become_user: "{{ansible_user}}"

- name: Copy aws credentials
  copy:
    dest: "/home/ubuntu/.s3cfg"
    owner: ubuntu
    group: ubuntu
    mode: 0600
    content: |
      [default]
      access_key = {{ AWSAccessKeyId }}
      secret_key = {{ AWSSecretKey }}