- name: Installing dependencies
  apt: name={{item}} state=installed
  with_items:
    - libcurl4-nss-dev

- name: Download aurora deb
  get_url:
    url: https://apache.bintray.com/aurora/ubuntu-{{ ansible_distribution_release }}/aurora-executor_0.20.0_amd64.deb
    dest: /tmp/aurora-executor_0.20.0_amd64.deb

- name: Install aurora
  apt:
    deb: /tmp/aurora-executor_0.20.0_amd64.deb

- name: restart executor
  systemd:
    name: thermos
    state: restarted
  become: yes
