- name: Stop dfs
  shell: /home/ubuntu/hadoop-2.9.2/sbin/stop-dfs.sh
  become: yes
  become_user: "{{ansible_user}}"

- name: Delete previous hdfs data
  file:
    path: /home/ubuntu/hadoop-2.9.2/dfs
    state: absent

- name: Format namenode
  shell: /home/ubuntu/hadoop-2.9.2/bin/hdfs namenode -format
  become: yes
  become_user: "{{ansible_user}}"

- name: Start dfs
  shell: /home/ubuntu/hadoop-2.9.2/sbin/start-dfs.sh
  become: yes
  become_user: "{{ansible_user}}"