- name: Fill mesos master settings
  lineinfile:
    path: /etc/default/mesos-slave
    line: "{{item}}"
  with_items:
    - "args+=( --advertise_ip={{ inventory_hostname }} )"
    - "args+=( --no-hostname_lookup )"
    - "args+=( --hostname=slave{{ groups['slaves'].index(inventory_hostname) + 1 }} )"

- name: Start mesos slave
  systemd:
    name: mesos-slave
    state: restarted